name: Deploy static content to Pages

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: pull lfs
        run: git lfs pull
      - name: verify glb
        run: |
          ls -lh maps/badwater.glb
          file maps/badwater.glb
          head -c 4 maps/badwater.glb | xxd

      - name: setup pages
        uses: actions/configure-pages@v5
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4